### ISSUE TITLE
Keyboard theme needs help

### ISSUE THREAD

**Issue by milogert** [srcery-colors/srcery-steam-deck#3]
At the moment the keyboard theme has a couple problems:

- [ ] Applied to not just the default theme.
- [ ] Not togglable.

**Comment by Tormak9970** [comment]
> At the moment the keyboard theme has a couple problems:
> 
>     * [ ]  Applied to not just the default theme.
> 
>     * [ ]  Not togglable.

I can try and whip up the styling later. Made a keyboard theme that allows full color customization already, so should be able to adapt that rather quickly

**Comment by Tormak9970** [comment]
PR #4 Contains the styling I came up with as well as the simplified method for handling keyboard theming

**Comment by milogert** [comment]
Thanks for the contribution @Tormak9970. Closing this one out as it's fixed. More keyboard changes are coming down the pike in #5
